builds:
  - main: ./main/main.go
    env:
        - CGO_ENABLED=0
    goos:
      - linux
      - windows

archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: binary

sign:
  artifacts: checksum

release:
  github:
    owner: Jaskaranbir
    name: "{{ .ProjectName }}"

changelog:
  sort: desc

dockers:
  - goos: linux
    goarch: amd64
    binary: app
    image: jaskaranbir/{{ .ProjectName }}
    tag_templates:
      - "{{ .Tag }}"
      - latest
